### ISSUE TITLE
Meterpreter & PrivEsc

### ISSUE THREAD

**Issue by LattePiuCyberSec** [pr0xy-8L4d3/EvilRAT#2]
Sorry for the n00b question.
Is it possibile to modify the script in order to retrive a meterpreter connection?
As it is, I can't do privilege escalation with Metasploit.

In any case, thanks for ur work!

**Comment by pr0xy-8L4d3** [comment]
I already tried in the past to modify it on the way you can obtain meterpereter session, but with no luck. I mean, it is hard to create meterpreter payload and not to be detected by AV. Maybe will try in near future again.

**Comment by LattePiuCyberSec** [comment]
Thank you for the quick response. Good luck!
